"""
LORA — Planner (Rule Engine)
=============================
Deterministic routing engine. Evaluates a priority-ordered set of
conditions against the instruction and context, and produces a RoutingPlan.

The Planner never answers. It produces a RoutingPlan. The ControllerAgent
executes the plan.

Inference is invoked in exactly one place: Priority 5 (episodic relevance).
Priorities 1–4 and 6 are pure rule evaluations — no model calls.

Reference: §4 of LOCALIST-Architecture.md
"""

from __future__ import annotations

import logging
import os
import re
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any, Callable

# file_op content/path/action derivation is dispatch-time logic owned by
# mcp_tool_dispatcher.py; reused here (not duplicated) so Priority 3's
# content-present-vs-generation-required split can never drift from what
# actually runs at dispatch time.
from mcp_tool_dispatcher import (
    _FILE_OP_PATH_PATTERNS,
    _derive_file_op_action,
    _derive_file_op_content,
    _derive_file_op_path,
)

if TYPE_CHECKING:
    from memory_manager import MemoryManager

logger = logging.getLogger(__name__)


def _cosine_similarity(a: list[float], b: list[float]) -> float:
    """Cosine similarity between two equal-length float vectors."""
    import math
    if len(a) != len(b) or not a:
        return 0.0
    dot    = sum(x * y for x, y in zip(a, b))
    norm_a = math.sqrt(sum(x * x for x in a))
    norm_b = math.sqrt(sum(x * x for x in b))
    if norm_a == 0.0 or norm_b == 0.0:
        return 0.0
    return dot / (norm_a * norm_b)


# ---------------------------------------------------------------------------
# RoutingPlan  (§4.4)
# ---------------------------------------------------------------------------

@dataclass
class RoutingPlan:
    """
    The output of the Planner. Consumed by ControllerAgent.handle_task().

    Fields
    ------
    agent :
        "wiki_agent" | "conversational_agent"
    fetch_episodic :
        True → retrieve from episodes table and inject into slot 4.
    fetch_rag :
        True → query_corpus() before responding; results populate slot 5.
    tools_to_call :
        Tool names in dispatch order. Empty list if no tools needed.
    write_episode :
        True → EpisodicMemoryWriter runs before the agent call.
    episode_type :
        Type hint for episodic extraction. None when write_episode is False.
    compound :
        True → multiple signal types detected; ControllerAgent sequences
        execution in priority order.
    graph_query :
        (direction, node_id, resolved_stem) when Priority 3c matched a
        structural graph lookup; None otherwise. direction is "incoming"
        or "outgoing". resolved_stem is carried alongside node_id so
        downstream consumers skip a second MemoryManager round-trip just
        to recover the display name.
    tool_signal_source :
        Provenance of tools_to_call, for per-turn auditability: "keyword"
        when a deterministic P3/P3b/compound match populated it,
        "classifier_fallback" when the feature-flagged P6-fallthrough
        tool-need classifier populated it (active mode only),
        "slash_command" when a leading "/chart"/"/research" token (Priority
        0) forced it, or None when tools_to_call is empty or was set by a
        code path that predates this attribution (e.g. P3c never sets
        tools_to_call, so it stays None there too).
    file_op_deferred :
        True → Priority 3 detected a file_op-shaped instruction whose
        content must be generated by the agent before the file can be
        written (e.g. "write a haiku about the sea and save it as
        haiku.md") rather than being supplied literally in the
        instruction (fenced/quoted text, or "with the content"/
        "containing"/"that says" phrasing). "file_op" is deliberately
        NOT added to tools_to_call in this case — there's nothing to
        dispatch yet, since the content doesn't exist at planning time.
        file_op_path/file_op_action carry the pre-resolved destination so
        a future controller step can dispatch file_op once generation
        completes. False for every other RoutingPlan, including file_op
        matches where the content was already present in the instruction
        (those still take the tools_to_call=["file_op"] path unchanged).
    file_op_path :
        Destination path for a deferred file_op, resolved the same way
        _derive_file_op_path() resolves it at dispatch time. None unless
        file_op_deferred is True.
    file_op_action :
        "write" or "append" — the file_op action for a deferred file_op,
        resolved the same way _derive_file_op_action() resolves it at
        dispatch time. None unless file_op_deferred is True.
    diff_target :
        Resolved wiki page stem (e.g. "localist-software-stack") when
        Priority 1b matched a diff-only wiki-update instruction and target
        resolution succeeded. None in every other case, including a P1b
        keyword match whose target resolution failed or was ambiguous
        (that case routes to conversational_agent for clarification
        instead — see Planner._priority1b_diff()). ControllerAgent wires
        this into the wiki_agent SubTask.context as "diff_target".
    """
    agent:          str
    fetch_episodic: bool
    fetch_rag:      bool
    tools_to_call:  list[str]  = field(default_factory=list)
    write_episode:  bool       = False
    episode_type:   str | None = None
    compound:       bool       = False
    priority:       int        = 6
    graph_query:    tuple[str, int, str] | None = None
    tool_signal_source: str | None = None
    file_op_deferred: bool       = False
    file_op_path:     str | None = None
    file_op_action:   str | None = None
    diff_target:      str | None = None


# ---------------------------------------------------------------------------
# Keyword sets  (§4.2)
# ---------------------------------------------------------------------------

# Priority 1 — ingest keywords (checked against lowercased instruction)
_INGEST_KEYWORDS: frozenset[str] = frozenset({
    "ingest",
    "process this file",
    "add to wiki",
    "index this",
})

# Priority 1b — diff-only wiki update trigger keywords (checked against
# lowercased instruction). Deliberately narrow and explicit, matching this
# module's existing "deterministic, no false-positive-risk" style for
# keyword sets (see _WEB_SEARCH_KEYWORDS comment). Only matched when
# Priority 1 (ingest) did not already fire.
_DIFF_KEYWORDS: frozenset[str] = frozenset({
    "update the wiki",
    "update page",
    "revise page",
    "modify page",
    "apply a diff to",
})

# Longest-first ordering for lead-phrase stripping in extract_diff_query(),
# mirroring _BACKLINK_LEAD_PHRASES/_OUTGOING_LEAD_PHRASES below — a shorter
# phrase must never shadow a longer, more specific one that is also a
# prefix of the instruction.
_DIFF_LEAD_PHRASES: tuple[str, ...] = tuple(
    sorted(_DIFF_KEYWORDS, key=len, reverse=True)
)

# Priority 2 — explicit memory command keywords
_MEMORY_KEYWORDS: frozenset[str] = frozenset({
    "remember that",
    "my preference is",
    "that's wrong",
    "the correct value is",
    "forget that",
    "mark complete",
    "that's no longer true",
})

# Priority 3 — web search trigger keywords
# Multi-word phrases carry no false-positive risk with _any_whole_word().
# Single words ("today", "recent", "news") are protected by \b anchors.
_WEB_SEARCH_KEYWORDS: frozenset[str] = frozenset({
    "latest",
    "current price",
    "current version",
    "current ceo",
    "current status",
    "current rate",
    "news",
    "recent",
    "web search",
    "do a search",
})

# Priority 3 — explicit-date web search signal, independent of both
# _WEB_SEARCH_KEYWORDS and _SEMANTIC_GATE_THRESHOLDS. A query that names a
# specific calendar date (month + year, with or without a day) is a
# qualitatively different signal from the fuzzy semantic gates below: the
# model structurally cannot verify a specific date from training alone, so
# this is close to a hard rule rather than a threshold judgment call. Added
# to close a live gap where "Look up TSM's July 16 2026 earnings..." had no
# keyword hit and scored 0.573 on lookup_request — just under the 0.60
# gate — so no tool fired and the model produced an empty completion with
# zero grounding. Deliberately requires a month name (full or abbreviated)
# paired with a year, or an ISO date, rather than a bare 4-digit year —
# a bare year alone is too weak a signal and risks false positives on
# version/model numbers ("Windows 2000", "the SR-2026 model").
_MONTH_NAMES: tuple[str, ...] = (
    "january", "february", "march", "april", "may", "june", "july",
    "august", "september", "october", "november", "december",
    "jan", "feb", "mar", "apr", "jun", "jul", "aug", "sep", "sept", "oct", "nov", "dec",
)
_MONTH_ALTERNATION = "|".join(_MONTH_NAMES)
_EXPLICIT_DATE_PATTERN = re.compile(
    rf"""
    \b(?:{_MONTH_ALTERNATION})\.?\s+\d{{1,2}}(?:st|nd|rd|th)?,?\s+(?:19|20)\d{{2}}\b
  | \b\d{{1,2}}(?:st|nd|rd|th)?\s+(?:{_MONTH_ALTERNATION})\.?,?\s+(?:19|20)\d{{2}}\b
  | \b(?:{_MONTH_ALTERNATION})\.?\s+(?:19|20)\d{{2}}\b
  | \b(?:19|20)\d{{2}}-\d{{2}}-\d{{2}}\b
    """,
    re.IGNORECASE | re.VERBOSE,
)


def _has_explicit_date(text: str) -> bool:
    """
    True when `text` names a specific calendar date (month + year, with an
    optional day, in either order; or an ISO YYYY-MM-DD date). See the
    _EXPLICIT_DATE_PATTERN comment above for the false-positive rationale.
    """
    return bool(_EXPLICIT_DATE_PATTERN.search(text))

# Priority 3b — factual query keywords (trigger web search when corpus misses)
_FACTUAL_QUERY_KEYWORDS: frozenset[str] = frozenset({
    "when did",
    "what year",
    "who founded",
    "who invented",
    "who created",
    "where was",
    "how many",
    "what is the",
    "which company",
    "who was the first",
    "what was the first",
})

# Priority 4 — explicit wiki/vault query triggers
_WIKI_QUERY_KEYWORDS: frozenset[str] = frozenset({
    "check the wiki",
    "search the wiki",
    "what's in my vault",
    "what is in my vault",
    "look in the wiki",
    "from the wiki",
    "in the wiki",
    "vault",
})

# Priority 3 — URL fetch trigger keywords (explicit only)
_FETCH_KEYWORDS: frozenset[str] = frozenset({
    "fetch this",
    "fetch the url",
    "fetch this url",
    "read this link",
    "read this url",
    "open this link",
    "summarize this url",
    "summarize this link",
    "extract this",
})

# Priority 3 — file operation trigger keywords
_FILE_OP_KEYWORDS: frozenset[str] = frozenset({
    "read the file",
    "read file",
    "open the file",
    "create a file",
})

# Priority 3 — chart generation trigger keywords
# Deliberately narrow and imperative-verb-first, matching the
# chart_keyword_clear category from the diagnostic corpus
# (diagnostics/diag_shadow_chart_toolcall.py) that measured cleanly against
# real model behavior — same "deterministic, no false-positive-risk" style
# as _WEB_SEARCH_KEYWORDS/_FILE_OP_KEYWORDS above. Do not add broader/vaguer
# phrases (e.g. bare "chart", "graph", "plot") without re-running that
# diagnostic's corpus against them — see the _SEARCH_NEGATIVE_FILTER
# comments above for why vague triggers cause false positives (e.g. "explain
# what a bar chart is" must stay negative).
#
# 2026-07-20: "turn this into a {chart|bar chart|line chart|pie chart|
# graph}" and "turn this into something visual" added — a real gap between
# what the diagnostic corpus had already validated and what shipped.
# "Turn this into a pie chart: Chrome 65, Safari 19, Firefox 8, Edge 6,
# Other 2" (chart_keyword_clear, expects_tool=True) and "Turn this into
# something visual: Q1 100, Q2 150, Q3 130, Q4 180" (chart_semantic_implicit,
# expects_tool=True) are both in _CORPUS with no keyword covering them —
# caught live when the pie-chart instruction fell through to P6 instead of
# firing the chart tool. "turn this into a bar/line chart" and "turn this
# into a graph" are added alongside the corpus-confirmed pie-chart phrasing
# as the same template's other chart-type slots (same reasoning
# "make a chart"/"make a bar chart"/"make a line chart"/"make a pie chart"
# above already cover all four slots of their own template) — not
# independently corpus-validated strings, but the same pattern with the
# type swapped. Do not widen "turn this into a" further (e.g. dropping the
# chart-type/visual suffix) without a fresh diagnostic run — see the
# comment above.
_CHART_KEYWORDS: frozenset[str] = frozenset({
    "chart this",
    "make a chart",
    "make a bar chart",
    "make a line chart",
    "make a pie chart",
    "plot this",
    "plot these",
    "graph this",
    "graph these",
    "visualize this",
    "visualize these",
    "turn this into a chart",
    "turn this into a bar chart",
    "turn this into a line chart",
    "turn this into a pie chart",
    "turn this into a graph",
    "turn this into something visual",
})

# Priority 0 — explicit slash-command tool bypass. A leading "/chart" or
# "/research" token forces that tool directly, ahead of every other
# priority: "/chart" bypasses _CHART_KEYWORDS matching, and "/research"
# bypasses both the research_intent semantic-upgrade threshold AND
# LOCALIST_RESEARCH_LOOP_ENABLED (normally required for "research" to ever
# enter tools_to_call at all — see _RESEARCH_LOOP_ENV_VAR below). See
# _priority0_slash_command().
_SLASH_COMMAND_TOOL_MAP: dict[str, str] = {
    "/chart":    "chart",
    "/research": "research",
}

# Diagnostic Slot 1 — canonical template groups for semantic search-intent scoring.
# These strings are embedded at startup and used only for cosine-similarity logging;
# they do not gate any routing decision until a threshold prompt replaces this comment.
_SEARCH_INTENT_TEMPLATES: dict[str, tuple[str, ...]] = {
    "explicit_search_action": (
        "search the web for this",
        "do a web search for this",
        "search online for this",
        "google this",
        "go look it up",
    ),
    "lookup_request": (
        "look up this",
        "look that up",
        "go ahead and look it up",
        "find information on this",
        "find out about this",
        # 2026-06-28: The 4 polite-imperative templates added 2026-06-25 caused a
        # confirmed, threshold-unfixable false-positive surface: 6/14 fresh adversarial
        # negatives scored 0.81–0.90, ABOVE every true positive's max (~0.62). Replaced
        # with Candidate Set 1 (object-specificity fix) per:
        #   diagnostics/reports/lookup_request_template_rework_2026-06-28.md
        #   diagnostics/reports/full_pertable_lr_set1_esa_2026-06-28.md
        # Effect: Cat D false positives 13/14 → 6/14; 3 true positives fully preserved
        # (3/3); 5 negative-filter-protected identity/greeting phrases unaffected.
        # KNOWN ACCEPTED RESIDUAL — 6/14 adversarial negatives remain gate-positive:
        #   D-verb-swap ×4: "Can you help me with this?", "Could you check this for me?",
        #                   "Would you look at this?", "Can you tell me about this?"
        #   D-modal-swap ×2: "Will you look into this?", "Do you mind looking at this?"
        # These fire via the modal-question scaffold; not eliminated by Set 1.
        "can you look up the release date for this",
        "could you look up what year this happened",
        "can you look up information about the latest Apple products",
        "could you find out the current stock price for me",
    ),
    "knowledge_request_open": (
        "what is this",
        "what do you know about this",
        "tell me about this",
        "explain this to me",
    ),
    "freshness_request": (
        "what's the latest on this",
        "what's the current status of this",
        "is there anything new about this",
    ),

    # New — a specialization of lookup_request: the user wants a specific,
    # extractable fact (price, spec, plan tier) run down, not a general
    # summary. Kept as its own group rather than folded into lookup_request
    # so it can carry its own threshold and be tuned independently, same
    # reasoning that already separates explicit_search_action (0.72) from
    # lookup_request (0.60). Only ever decides web_search -> research
    # upgrade in _priority3_tool (see _RESEARCH_INTENT_THRESHOLD below) —
    # never gates whether a tool fires at all, so it is intentionally not
    # part of _SEMANTIC_GATE_THRESHOLDS.
    #
    # v2 (2026-07-16): every template anchors on an explicit lookup/search
    # verb + a concrete object, replacing v1's bare interrogative forms
    # ("what does this cost") that syntactically collided with subjective
    # price-opinion utterances ("is this worth the price") — see
    # diagnostics/reports/research_intent_threshold_assessment_2026-07-16.md.
    "research_intent": (
        "look up the pricing for this product",
        "find out how much this subscription costs",
        "search for the price of this item",
        "check the current price of this plan",
        "find the pricing tiers for this service",
        "track down how much this product costs",
        "look up the specs and price for this product",
        "find the cost of this plan per month",
    ),
}

# Mirrors _SEARCH_NEGATIVE_FILTER below, scoped to research_intent's own
# collision: subjective price-opinion phrasing ("is this worth the price")
# shares cost/price vocabulary with real lookup requests but isn't asking
# for a number. The 2026-07-16 v1 diagnostic found this collision was
# threshold-unfixable (the negative scored above every true positive), the
# same failure shape as lookup_request's 2026-06-25 incident — so it's
# handled the same way: a substring pre-filter, not a threshold. Checked
# (alongside _SEARCH_NEGATIVE_FILTER, combined as _ALL_SEARCH_NEGATIVE_
# FILTERS below) in _semantic_search_intent() — see that method's 2026-07-16
# redesign docstring for the current two-step conflict-resolution behavior;
# a match no longer unconditionally skips scoring. The v2 diagnostic
# (research_intent_threshold_assessment_2026-07-16-v2.md) confirmed this
# fully resolves the raw collision: all 4 test utterances that match are
# intercepted before they can reach any gate absent a tie-break override.
_RESEARCH_NEGATIVE_FILTER: frozenset[str] = frozenset({
    "worth the price",
    "too expensive",
    "lot of money for",
    "can't believe how expensive",
})

_SEARCH_NEGATIVE_FILTER: frozenset[str] = frozenset({
    "search your memory",
    "search my previous messages",
    "search this conversation",
    "what did i just say",
    "what did you just say",
    "why didn't you search",
    "why did you search",
    "did you search",
    "what tool did you use",
    # 2026-06-26: identity/capability questions confirmed as false positives via
    # diagnostics/score_lookup_request_templates.py — these utterances cross the
    # lookup_request 0.60 gate due to syntactic (not semantic) similarity with the
    # four question-form templates added 2026-06-25 ("can you look up", etc.).
    "who are you",
    "what are you",
    "what can you do",
    "what can you help with",
    "what do you do",
    # 2026-06-27: greeting false positives confirmed via live diagnostic
    # (diagnostics/score_greeting_collisions.py) — these utterances cross
    # the lookup_request 0.60 gate. Live finding: "Hey LORA!" scored 0.612
    # on lookup_request, the same gate the 2026-06-25 update B threshold-
    # lowering commit named as the trigger for revisit on any live false
    # positive. Follow-up diagnostic ruled out length and greeting-category
    # as the operative mechanism; per-utterance data showed only a small
    # set of specific lead tokens ("hey", "hi", "what's up") carry the
    # anomalous score, not greetings as a class ("good morning", "hello"
    # do not collide). Bare "hi" and "hey" are deliberately NOT added here:
    # under this filter's substring-match mechanism, "hi" collides with
    # common words ("history", "this", "high", "vehicle", etc.) and would
    # silently suppress the semantic gate on unrelated legitimate queries.
    # "hey" has at least one known collision ("they"). Both are tracked as
    # a separate open item pending either a word-boundary-matched filter
    # path or a different mechanism — see LOCALIST-Architecture.md §10.4
    # open items. This entry covers only the multi-word forms, which are
    # safe under substring matching with no collisions found in testing.
    "hey lora",
    "hi there",
    "hey there",
    "what's up",
})

# Combined lookup set for the single substring-match pass in
# _semantic_search_intent()'s post-scoring negative-filter check (2026-07-16
# redesign) — one membership test covers both filters' phrases rather than
# two separate passes, since post-redesign both are handled identically
# (matched-phrase lookup -> conflict check -> optional tie-break), unlike
# the old pre-scoring behavior where they were checked as separate
# early-return blocks.
_ALL_SEARCH_NEGATIVE_FILTERS: frozenset[str] = _SEARCH_NEGATIVE_FILTER | _RESEARCH_NEGATIVE_FILTER

# Relevance threshold for Priority 4 corpus scoring
_CORPUS_SCORE_THRESHOLD: float = 0.55

# Slot [Fix 1] — semantic search-intent gating thresholds.
# Derived from Diagnostic 2's live-backend score table (18 real
# utterances against mlx-community/embeddinggemma-300m-4bit).
# knowledge_request_open and freshness_request are deliberately
# excluded from gating — see Diagnostic 2 findings: a non-search
# utterance ("Explain this code to me.") scored 0.795 on
# knowledge_request_open, higher than 5 of 10 real positive
# paraphrases, because that group's templates are generically
# conversational. freshness_request showed one ambiguous negative
# (0.642, inside the positive range) and has not been independently
# stress-tested. Both groups remain computed and logged for future
# tuning but must never gate tools_to_call until separately re-evaluated.
#
# 2026-06-25 update A (§8.8 Open Item 11): lookup_request templates expanded
# from 5 to 9. The original 5 were bare imperatives with vague pronoun
# objects ("look up this", "look that up", etc.); they did not represent
# the "Can/Could you + look up/look into + [specific object]" question-form
# frame. Three live utterances using that frame scored 0.593, 0.598, and
# 0.598 on lookup_request — consistently below the 0.65 gate — causing
# gate_fired=False and no web_search dispatch. Four new templates appended:
# "can you look up", "can you look that up for me", "could you look up",
# "can you look into this for me". This was a template-coverage fix, not a
# threshold adjustment; the 0.65 threshold was deliberately left unchanged.
#
# 2026-06-25 update B (§10.4 Open Item 3 revisit, §8.8 Open Item 11):
# lookup_request threshold lowered from 0.65 to 0.60. Live re-verification
# after update A showed the same three utterances scored 0.608, 0.621, and
# 0.617 — a real, consistent improvement (+0.015 to +0.023) but still below
# the 0.65 gate. Template coverage alone cannot close this remaining gap for
# this phrasing family at this scale of addition. The 0.03–0.04 shortfall
# across all three utterances matches Open Item 3's stated revisit criterion
# ("if live false negatives are observed"). explicit_search_action (0.68) is
# NOT changed. Known risk: the original 18-utterance diagnostic pass did not
# retain per-utterance scores for lookup_request's adversarial negatives, so
# the margin to the new 0.60 line is unknown. Accepted and named risk — any
# live false positive on lookup_request is the trigger to revisit this value.
_SEMANTIC_GATE_THRESHOLDS: dict[str, float] = {
    # 2026-06-28: raised from 0.68 → 0.72 per
    # diagnostics/reports/explicit_search_action_margin_assessment_2026-06-28.md.
    # The single template "go look it up" (bare verb "look") collided with "look at"/
    # "look into" phrasing in 2 adversarial negatives at ESA 0.69–0.70. Zero cost to
    # true positives: Cat C max ESA score = 0.58, well under either threshold.
    # Per Michael's decision: shipping to observe live behavior for several days before
    # treating as final — not a permanently closed item.
    "explicit_search_action": 0.72,
    "lookup_request": 0.60,
}


# ---------------------------------------------------------------------------
# Tuned-embedding-model guard
#
# Every threshold above (_SEMANTIC_GATE_THRESHOLDS, and _RESEARCH_INTENT_
# THRESHOLD further below) and both negative-filter substring pre-filters
# (_SEARCH_NEGATIVE_FILTER, _RESEARCH_NEGATIVE_FILTER) were tuned against
# cosine scores produced by this specific embedding model. Cosine similarity
# is not portable across embedding models — the same utterance pair can
# score very differently under a different model's geometry, which silently
# flips gate_fired without raising anything. Confirmed live 2026-07-16: the
# identical lookup_request utterance scored 0.7119 under
# mlx-community/embeddinggemma-300m-4bit vs 0.578 under nomic-embed-text —
# enough to cross the 0.60 lookup_request gate one way and not the other.
#
# Measured against (all assumed this exact model):
#   - the lookup_request / explicit_search_action threshold history in the
#     comments above (2026-06-25 update A/B, 2026-06-28 ESA raise)
#   - diagnostics/reports/research_intent_threshold_assessment_2026-07-16.md
#   - diagnostics/reports/research_intent_threshold_assessment_2026-07-16-v2.md
#   - diagnostics/reports/negative_filter_tiebreak_assessment_2026-07-16.md
#
# See Planner.__init__ / _semantic_search_intent() for the runtime guard this
# constant backs, and docs/architecture/16-runtime-backend-layer.md §16.4.
_TUNED_EMBEDDING_MODEL: str = "mlx-community/embeddinggemma-300m-4bit"


# ---------------------------------------------------------------------------
# research_intent upgrade  (web_search -> research, plain on/off — no
# shadow phase)
#
# Unlike the P6-fallthrough classifier below, this doesn't ship shadow-first.
# 2026-07-16 decision: single-user, non-production app — the shadow-first
# rollout discipline used elsewhere in this file exists to de-risk a
# threshold change against real multi-user traffic before it can affect a
# live answer; that risk doesn't apply here. Plain on/off switch instead,
# read at call time (not cached) so flipping backend/.env doesn't require
# reconstructing the Planner — same rationale as _TOOL_FALLBACK_ENV_VAR.
# ---------------------------------------------------------------------------
_RESEARCH_LOOP_ENV_VAR: str = "LOCALIST_RESEARCH_LOOP_ENABLED"

# Picked from the v2 diagnostic trade-off table
# (diagnostics/reports/research_intent_threshold_assessment_2026-07-16-v2.md):
# 9/10 true positives survive (only "What's the going rate for a plumber in
# this area?", itself a marginal non-brand-specific phrasing, drops out),
# and only 2/16 FP-pool items leak — both Category L generic lookups that
# already trigger web_search via lookup_request regardless, so a false
# positive here just burns extra bounded loop iterations rather than
# producing a wrong answer. That asymmetry (false positive = wasted
# latency, capped by _MAX_RESEARCH_ITERATIONS; false negative = today's
# existing plain-web_search behavior, not broken) is why full T/FP
# separation wasn't chased further. No threshold in the scanned range
# achieved full separation — see the report for the complete trade-off.
# Revisit directly if 0.65 turns out wrong against live usage, same as how
# lookup_request's threshold was revised from 0.65 to 0.60.
_RESEARCH_INTENT_THRESHOLD: float = 0.65


# ---------------------------------------------------------------------------
# Negative-filter conflict resolution  (2026-07-16 redesign)
#
# _semantic_search_intent() checks _ALL_SEARCH_NEGATIVE_FILTERS AFTER
# scoring, not before — see that method's docstring for the full rationale.
# This prompt backs the single bounded inference call
# (_resolve_negative_filter_conflict) made only when a filter phrase
# matched AND some gated group's score cleared its own threshold anyway;
# validated in diagnostics/reports/negative_filter_tiebreak_assessment_
# 2026-07-16.md (11/11 accuracy on the operationally-reachable subset)
# before being wired in here.
# ---------------------------------------------------------------------------
_NEGATIVE_FILTER_TIEBREAK_SYSTEM_PROMPT: str = (
    "You are a routing classifier, not a conversational assistant. The "
    "instruction below matched a known phrase pattern that is usually NOT "
    "a request to search for or look up information (e.g. a subjective "
    "opinion, a greeting, an identity question) but also scored high on "
    "semantic similarity to real search-intent phrasing — an ambiguous "
    "case. Decide which one it actually is. Respond with exactly one "
    "word: lookup or other."
)


# ---------------------------------------------------------------------------
# P6-fallthrough tool-need classifier  (feature-flagged, shadow-first)
#
# Fires only when P1, P2, P3/3b/3c, and P4 have all found no match for the
# turn — i.e. routing is about to fall through past Priority 5 toward
# Priority 6. Two hard gates run before any model call (see
# Planner._classify_tool_fallback); the flag below is a third, coarser gate
# checked before that method is even invoked.
# ---------------------------------------------------------------------------

# Read at call time (not cached at import/construction) so tests and ops
# tooling can flip modes without reconstructing the Planner instance.
_TOOL_FALLBACK_ENV_VAR: str = "LOCALIST_TOOL_FALLBACK_CLASSIFIER"

# Read at call time, same rationale as _TOOL_FALLBACK_ENV_VAR. Gates whether
# _classify_tool_fallback()'s Gate 1 (prior-turn tool state) check runs at
# all; default ("on"/unset) preserves existing behavior exactly. Setting
# this to "off" lets live testing observe what Gate 1 would have blocked,
# via the "would have gated if enabled" log line.
_GATE1_ENV_VAR: str = "LOCALIST_TOOL_FALLBACK_GATE1"

_TOOL_FALLBACK_VALID_MODES: frozenset[str] = frozenset({"off", "shadow", "active"})

# The only values the classifier prompt is allowed to resolve to. Anything
# else — empty string, prose, garbage — parses to None, identical to "none".
_TOOL_FALLBACK_TOOL_NAMES: frozenset[str] = frozenset({
    "web_search", "file_op", "url_fetch",
})

_TOOL_FALLBACK_SYSTEM_PROMPT: str = (
    "You are a routing classifier, not a conversational assistant. Given a "
    "user instruction, decide whether answering it requires calling an "
    "external tool. Respond with exactly one word and nothing else: "
    "web_search, file_op, url_fetch, or none."
)


# ---------------------------------------------------------------------------
# Graph-query extraction and name resolution  (P3c, Phase C Step 3a)
#
# extract_graph_query() and resolve_graph_target() are pure, stateless
# functions with zero MemoryManager dependency. The caller (ControllerAgent /
# route(), wired in Step 3b) injects the real stem list at call time.
# ---------------------------------------------------------------------------

# Pattern B — incoming backlink lead-phrases, sorted longest-first.
# Longest-first ordering is load-bearing: a shorter phrase must not
# shadow a longer, more specific one that is also a prefix of the
# instruction (even if no collision exists in the current set, any
# future addition could introduce one).
_BACKLINK_LEAD_PHRASES: tuple[str, ...] = (
    "show me backlinks for",
    "what pages link to",
    "backlinks for",
    "what links to",
    "what references",
    "what mentions",
)

# Pattern C — outgoing lead-phrases, same longest-first principle.
_OUTGOING_LEAD_PHRASES: tuple[str, ...] = (
    "show outgoing links for",
    "outgoing links for",
    "what links from",
    "links from",
)

# Token-overlap stopwords for Tier 2 name resolution.
_GRAPH_STOPWORDS: frozenset[str] = frozenset({
    "the", "a", "an", "of", "to", "in", "on", "for", "is", "are",
    "and", "or", "page", "pages", "about", "that",
})

# Pattern A compiled regex (module-level, evaluated once at import time).
_PATTERN_A_OUTGOING: re.Pattern[str] = re.compile(
    r"what does (.+?) link to\??\.?$", re.IGNORECASE
)


def _normalize_graph_text(text: str) -> str:
    # Identical to wiki_agent._validate_links() / build_graph._normalize():
    # link_text.lower().replace(" ", "-").
    # .strip() is added here because remainder may carry incidental leading/
    # trailing whitespace that the write-time normalizer never sees (link_text
    # there always comes pre-trimmed from XML parsing).
    return text.lower().strip().replace(" ", "-")


def extract_graph_query(instruction: str) -> tuple[str, str] | None:
    """
    Attempt to extract a (direction, remainder) pair from `instruction`
    using three deterministic patterns. Returns None if no pattern matches.

    direction : "incoming" | "outgoing"
    remainder : whatever text follows/is captured by the matched
                pattern — passed directly to resolve_graph_target()
                with no further cleanup, even if empty.
    """
    instruction = instruction.strip()

    # Pattern A is checked first because it is a regex anchored at both
    # ends (re.match + $ anchor) and syntactically more specific than B/C's
    # startswith checks. Checking it first avoids any ambiguity on inputs
    # that match "what does X link to" — no B/C phrase can compete with that
    # anchored form, but testing A before B/C makes the priority explicit.
    m = _PATTERN_A_OUTGOING.match(instruction)
    if m:
        return ("outgoing", m.group(1).strip())

    # Normalize for B and C: lowercase, strip surrounding whitespace, then
    # strip trailing punctuation so "What links to X?" and "what links to X"
    # reach the same startswith comparison.
    normalized = instruction.strip().lower().rstrip("?.")

    # Pattern B — incoming: longest-first ordering prevents a shorter phrase
    # from matching before a longer, more specific one.
    for phrase in _BACKLINK_LEAD_PHRASES:
        if normalized.startswith(phrase):
            return ("incoming", normalized[len(phrase):].strip())

    # Pattern C — outgoing: same longest-first principle as Pattern B.
    for phrase in _OUTGOING_LEAD_PHRASES:
        if normalized.startswith(phrase):
            return ("outgoing", normalized[len(phrase):].strip())

    return None


def extract_diff_query(instruction: str) -> str | None:
    """
    Attempt to extract the page-naming remainder from `instruction` for a
    Priority 1b diff-only wiki-update instruction. Returns None if no
    _DIFF_KEYWORDS lead phrase matches.

    Mirrors extract_graph_query()'s Pattern B/C lead-phrase stripping:
    normalize (lowercase, strip, drop trailing punctuation), then check
    _DIFF_LEAD_PHRASES longest-first so a shorter phrase never shadows a
    longer, more specific one. The returned remainder is passed directly to
    resolve_graph_target() with no further cleanup — that pipeline's Tier 1
    substring match handles a remainder that also carries trailing
    free-text description (e.g. "page x to reflect the new backend"),
    since the target stem still appears as a substring of the normalized
    remainder.
    """
    normalized = instruction.strip().lower().rstrip("?.")
    for phrase in _DIFF_LEAD_PHRASES:
        if normalized.startswith(phrase):
            return normalized[len(phrase):].strip()
    return None


def resolve_graph_target(
    remainder:       str,
    candidate_stems: list[str],
) -> str | None:
    """
    Resolve `remainder` (raw extracted text) against `candidate_stems`
    (a list of existing page stems, e.g. ["how-localist-works",
    "localist-build-order", ...]) using a three-tier deterministic
    pipeline. Returns the single matching stem, or None if resolution
    is ambiguous or finds no match (both cases are identical from the
    caller's perspective — never distinguish "zero" from "multiple").
    """
    normalized = _normalize_graph_text(remainder)

    # Tier 1 — symmetric substring match.
    # Match if: normalized remainder is a substring of the stem, OR the
    # stem is a substring of the normalized remainder (either direction).
    tier1 = [
        stem for stem in candidate_stems
        if normalized in stem or stem in normalized
    ]
    if len(tier1) == 1:
        return tier1[0]
    if len(tier1) > 1:
        # Multi-match: ambiguous. Never tiebreak — return None immediately.
        return None
    # Zero Tier 1 matches → fall through to Tier 2.

    # Tier 2 — token-overlap fallback (only reached when Tier 1 found zero).
    query_tokens = set(normalized.split("-")) - _GRAPH_STOPWORDS
    if len(query_tokens) < 2:
        # Too few meaningful tokens to score reliably; skip Tier 2 entirely
        # and fall through to Tier 3 (return None). This is the "skipped,
        # not scored" path — a low ratio is not the reason for the None here.
        return None

    # Asymmetric ratio: intersection / query-token count (NOT Jaccard).
    # Rewards stems where most of the query's meaningful words are present;
    # does not penalise stems for having more tokens than the query.
    tier2 = [
        stem for stem in candidate_stems
        if len(query_tokens & set(stem.split("-"))) / len(query_tokens) >= 0.5
    ]
    if len(tier2) == 1:
        return tier2[0]
    return None  # zero or ambiguous — Tier 3 fallthrough (return None)


# ---------------------------------------------------------------------------
# Planner
# ---------------------------------------------------------------------------

class Planner:
    """
    Rule engine that produces a RoutingPlan from an instruction and context.

    Priority order (first match wins):
      1.  Ingest signal      — deterministic keyword/context check
      1b. Diff-only update   — deterministic keyword check + graph-stem
                               resolution; only reached when P1 didn't match
      2.  Memory command     — deterministic keyword check
      3c. Graph-query        — structural link lookup; wins over web_search
                               but defers to file_op/url_fetch (inline guard)
      3.  Tool signal        — deterministic keyword check
      3b. Factual query      — keyword + corpus miss → web_search
      4.  Corpus signal      — deterministic score threshold check
      5.  Episodic relevance — single bounded inference call (added in 3.3)
      -.  Tool-fallback classifier — feature-flagged, shadow-first bounded
          inference call; only reached when P1–P5 all found no match
          (§ P6-fallthrough tool-need classifier). Off by default.
      6.  Direct answer      — fallback (added in 3.4)

    The Planner never calls agents, never writes to the database,
    and never assembles a prompt for the final answer.

    Parameters
    ----------
    runtime :
        RuntimeClient. Used for the Priority 5 inference call, and — only
        when LOCALIST_TOOL_FALLBACK_CLASSIFIER is "shadow" or "active" —
        the P6-fallthrough tool-need classifier's bounded inference call.
        Not used in Priority 1, 2, 4, or 6, and in Priority 3 only for
        negative-filter conflict resolution (2026-07-16 — see
        _resolve_negative_filter_conflict, reached from
        _semantic_search_intent when a _SEARCH_NEGATIVE_FILTER /
        _RESEARCH_NEGATIVE_FILTER phrase matches AND a gated group's score
        clears its own threshold anyway) — never for the base P3 keyword/
        semantic routing decision itself, and validated empirically before
        being wired in (diagnostics/reports/
        negative_filter_tiebreak_assessment_2026-07-16.md: 11/11 accuracy
        on the operationally-reachable subset).
    memory_manager :
        Optional MemoryManager. Required for Priority 4 corpus scoring.
        When absent, Priority 4 is skipped (no corpus to query).
    embedding_model_name :
        Name of the embedding model actually producing embed_fn's vectors
        (e.g. "mlx-community/embeddinggemma-300m-4bit"), or None when no
        embedding source is configured at all (keyword-only mode — embed_fn
        is also None in that case, so semantic scoring is already
        short-circuited). When set and it does not match
        _TUNED_EMBEDDING_MODEL, semantic search-intent gating is disabled
        for this Planner instance — see the module-level comment above
        _TUNED_EMBEDDING_MODEL for why cosine-similarity thresholds don't
        transfer across embedding models.
    """

    # Class-level aliases so callers can access via instance (e.g. p._WEB_SEARCH_KEYWORDS)
    _WEB_SEARCH_KEYWORDS:    frozenset[str]    = _WEB_SEARCH_KEYWORDS
    _FILE_OP_KEYWORDS:       frozenset[str]    = _FILE_OP_KEYWORDS
    _CHART_KEYWORDS:         frozenset[str]    = _CHART_KEYWORDS
    _GATE1_ENV_VAR:          str               = _GATE1_ENV_VAR
    _SLASH_COMMAND_TOOL_MAP: dict[str, str]    = _SLASH_COMMAND_TOOL_MAP

    def __init__(
        self,
        runtime:              Any,
        memory_manager:       "MemoryManager | None" = None,
        embed_fn:             Callable[[str], list[float]] | None = None,
        embedding_model_name: str | None = None,
    ) -> None:
        self._runtime        = runtime
        self._memory_manager = memory_manager
        self._embed_fn       = embed_fn

        # Guard against silently-invalid semantic gating (docs/architecture/
        # 16-runtime-backend-layer.md §16.4): every threshold in this file
        # was tuned against _TUNED_EMBEDDING_MODEL's cosine geometry. A
        # different active embedding model means those thresholds have no
        # validated meaning, so gating is disabled rather than left to
        # silently over/under-fire. None (no embedding source configured at
        # all) is not a mismatch — embed_fn is already None in that case,
        # which already short-circuits semantic scoring.
        self._embedding_model_name     = embedding_model_name
        self._semantic_gating_disabled = False
        if embedding_model_name is not None and embedding_model_name != _TUNED_EMBEDDING_MODEL:
            logger.warning(
                "Planner: active embedding model %r does not match the model "
                "semantic-gating thresholds were tuned against (%r) — "
                "disabling semantic search-intent gating for this session. "
                "The thresholds in _SEMANTIC_GATE_THRESHOLDS / "
                "_RESEARCH_INTENT_THRESHOLD have no validated meaning against "
                "embeddings from a different model.",
                embedding_model_name, _TUNED_EMBEDDING_MODEL,
            )
            self._semantic_gating_disabled = True

        # Session state for Priority 5 caching (§4.3)
        # _episodic_injected: True once episodic bullets have been injected
        #   this session; causes all further Priority 5 checks to return True
        #   without an inference call (relevance assumed to persist).
        # _episodic_cache_pairs: parallel list of (embedding, result)
        #   pairs used for cosine similarity lookup, since dict keys cannot
        #   be float lists.
        self._episodic_injected: bool = False
        self._episodic_cache_pairs: list[tuple[list[float], bool]] = []

        # Gate 1 state for the P6-fallthrough tool-need classifier — the
        # tools_to_call resolved by the most recently completed route() call.
        # Updated automatically at the end of every route() invocation (see
        # record_tools_fired()), mirroring the _episodic_injected pattern:
        # Planner is a single long-lived instance for the process, so this
        # is in-memory only, not persisted across restarts.
        self._last_turn_tools_fired: list[str] = []

        # Diagnostic Slot 1 — flat list of (group_name, vector) pairs, one per
        # template string across all groups in _SEARCH_INTENT_TEMPLATES.
        # Only populated when embed_fn is available; left empty on failure so
        # _semantic_search_intent() safely returns None without logging noise.
        self._template_embeddings: list[tuple[str, list[float]]] = []
        if embed_fn is not None:
            try:
                for group_name, phrases in _SEARCH_INTENT_TEMPLATES.items():
                    for phrase in phrases:
                        vec = embed_fn(phrase)
                        self._template_embeddings.append((group_name, vec))
                logger.debug(
                    "Planner: pre-embedded %d search-intent templates across %d groups.",
                    len(self._template_embeddings), len(_SEARCH_INTENT_TEMPLATES),
                )
            except Exception as exc:  # noqa: BLE001
                logger.warning(
                    "Planner: failed to embed search-intent templates — "
                    "semantic search-intent check will be skipped. Error: %s", exc,
                )
                self._template_embeddings = []

    # -----------------------------------------------------------------------
    # Public API
    # -----------------------------------------------------------------------

    def mark_episodic_injected(self) -> None:
        """
        Signal that episodic bullets were injected into the prompt this session.

        After this is called, Priority 5 will return fetch_episodic=True for
        all subsequent instructions in the same session without making another
        inference call. Relevance is assumed to persist within a session.

        Called by ControllerAgent after a successful episodic retrieval and
        prompt injection.
        """
        self._episodic_injected = True
        logger.debug("Planner: episodic_injected flag set for this session.")

    def record_tools_fired(self, tools: list[str]) -> None:
        """
        Record the tools_to_call resolved for the turn that just finished
        routing, so the next route() call's Gate 1 check (P6-fallthrough
        tool-need classifier) can see it deterministically.

        Called automatically by route() after every turn — this is not
        something callers need to invoke manually in production. It is
        exposed publicly so tests can seed a "prior turn" fixture directly.
        """
        self._last_turn_tools_fired = list(tools)
        logger.debug(
            "Planner: record_tools_fired — last_turn_tools_fired=%r.",
            self._last_turn_tools_fired,
        )

    def _detect_compound(
        self,
        lowered: str,
        context: dict[str, Any],
    ) -> RoutingPlan | None:
        """
        Detect compound instructions that trigger multiple priority conditions
        simultaneously and require special resolution (§4.5).

        Currently handles one compound case:

        Tool + Ingest
        -------------
        Condition: instruction matches both Priority 1 (ingest) AND Priority 3
        (web search tool).
        Resolution: wiki_agent with tools_to_call=["web_search"], compound=True.
        The ControllerAgent will execute the web_search tool first and pass
        the result as context to WikiAgent.

        Returns a RoutingPlan if a compound pattern is detected, or None if
        the instruction should proceed through normal priority evaluation.
        """
        has_ingest = (
            "raw_path" in context
            or any(kw in lowered for kw in _INGEST_KEYWORDS)
        )
        has_web_search = bool(self._any_whole_word(_WEB_SEARCH_KEYWORDS, lowered))

        if has_ingest and has_web_search:
            logger.debug(
                "Planner: compound detected — Tool + Ingest "
                "(ingest=%s, web_search=%s).",
                has_ingest, has_web_search,
            )
            return RoutingPlan(
                agent          = "wiki_agent",
                fetch_episodic = False,
                fetch_rag      = False,
                tools_to_call  = ["web_search"],
                compound       = True,
                tool_signal_source = "keyword",
            )

        return None

    def _priority0_slash_command(self, lowered: str) -> RoutingPlan | None:
        """
        Priority 0 — explicit slash-command tool bypass.

        A leading "/chart" or "/research" token (case-insensitive, either
        the entire instruction or followed by whitespace) forces that tool
        directly, short-circuiting every other priority — including P3's
        _CHART_KEYWORDS keyword match and the research_intent semantic-
        upgrade threshold / LOCALIST_RESEARCH_LOOP_ENABLED gate that
        normally has to be on for "research" to ever enter tools_to_call at
        all (§18.2). Runs before _detect_compound() and every other
        priority evaluation, so it wins even on an instruction that would
        also have matched further down.

        Only a LEADING token counts: a mid-sentence occurrence ("what's a
        good site to /chart my finances") does not match.

        The leading slash token is deliberately NOT stripped from the
        instruction text passed down to tools_to_call's dispatch — this
        RoutingPlan carries only the tool name; instruction stripping is
        left as a separate concern (see the Claude Code prompt that
        introduced this feature).

        Returns a RoutingPlan or None if no match.
        """
        lowered_stripped = lowered.strip()
        for command, tool_name in _SLASH_COMMAND_TOOL_MAP.items():
            if lowered_stripped == command or lowered_stripped.startswith(command + " "):
                logger.debug(
                    "Planner: Priority 0 matched — slash command %r forcing "
                    "tool %r.", command, tool_name,
                )
                return RoutingPlan(
                    agent          = "conversational_agent",
                    fetch_episodic = False,
                    fetch_rag      = False,
                    tools_to_call  = [tool_name],
                    compound       = True,
                    priority       = 0,
                    tool_signal_source = "slash_command",
                )
        return None

    def route(
        self,
        instruction: str,
        context:     dict[str, Any],
    ) -> RoutingPlan:
        """
        Evaluate priorities 1–6 in order and return the first matching plan.

        Thin wrapper around _route_impl(): records the resolved plan's
        tools_to_call after every call (record_tools_fired()) so the next
        turn's P6-fallthrough tool-need classifier Gate 1 check has a
        deterministic, in-memory view of "did the immediately preceding
        turn already fire a tool" — no new dependency, no context/DB
        plumbing required.

        Parameters
        ----------
        instruction :
            The raw user instruction string.
        context :
            The task context dict (may contain raw_path, wiki_dir, etc.).

        Returns
        -------
        RoutingPlan
            Never raises. Guaranteed to return a valid plan.
        """
        plan = self._route_impl(instruction, context)
        self.record_tools_fired(plan.tools_to_call)
        return plan

    def _route_impl(
        self,
        instruction: str,
        context:     dict[str, Any],
    ) -> RoutingPlan:
        """Priority evaluation body for route() — see route() for the public contract."""
        lowered = instruction.lower()

        # Priority 0 — explicit slash-command tool bypass. Must run before
        # compound detection and every other priority so a leading
        # "/chart"/"/research" always wins, regardless of what P3 (or the
        # research-loop flag) would otherwise decide for the same text.
        plan = self._priority0_slash_command(lowered)
        if plan is not None:
            return plan

        # Compound detection — must run before priority evaluation
        plan = self._detect_compound(lowered, context)
        if plan is not None:
            return plan

        # Priority 1 — Ingest signal
        plan = self._priority1_ingest(lowered, context)
        if plan is not None:
            return plan

        # Priority 1b — Diff-only wiki update (must run before Priority 2 so
        # both "write to storage" intents — ingest and diff — stay
        # deterministic and ahead of memory commands; only reached when
        # Priority 1 did not already match)
        plan = self._priority1b_diff(instruction, lowered)
        if plan is not None:
            return plan

        # Priority 2 — Explicit memory command
        plan = self._priority2_memory(lowered)
        if plan is not None:
            return plan

        # Priority 3c — Graph-query (runs before P3 so a graph-query wins over a
        # web_search-only P3 match; P3c's inline guard defers to P3 when
        # file_op/url_fetch signals are present)
        plan = self._priority3c_graph_query(instruction, lowered)
        if plan is not None:
            return plan

        # Priority 3 — Tool signal
        plan = self._priority3_tool(lowered, instruction)
        if plan is not None:
            return plan

        # Priority 3b — Factual query + corpus miss
        plan = self._priority3b_factual(instruction, lowered)
        if plan is not None:
            return plan

        # Priority 4 — Corpus signal
        plan = self._priority4_corpus(lowered, instruction)
        if plan is not None:
            # P4 matched — also run P5 to check episodic relevance.
            # If both match, merge into a compound plan so the controller
            # fetches both RAG context and episodic memory for this turn.
            p5 = self._priority5_episodic(instruction)
            if p5 is not None:
                logger.debug(
                    "Planner: P4+P5 compound — fetch_rag=True fetch_episodic=True."
                )
                plan.fetch_episodic = True
            return plan

        # Priority 5 — Episodic relevance (single bounded inference call)
        plan = self._priority5_episodic(instruction)
        if plan is not None:
            return plan

        # P6-fallthrough tool-need classifier — feature-flagged, shadow-first.
        # Only reached when P1, P2, P3/3b/3c, P4, and P5 have all found no
        # match. Off by default: _maybe_tool_fallback_classifier() returns
        # None immediately without calling _classify_tool_fallback() at all.
        plan = self._maybe_tool_fallback_classifier(instruction, context)
        if plan is not None:
            return plan

        # Priority 6 — Direct answer fallback
        return self._priority6_direct()

    # -----------------------------------------------------------------------
    # Priority 1 — Ingest signal  (§4.2, Priority 1)
    # -----------------------------------------------------------------------

    def _priority1_ingest(
        self,
        lowered: str,
        context: dict[str, Any],
    ) -> RoutingPlan | None:
        """
        Match condition: raw_path key present in context OR ingest keyword
        in lowercased instruction.

        Returns a RoutingPlan routed to wiki_agent, or None if no match.
        fetch_rag and fetch_episodic are explicitly False — ingest is never
        augmented with retrieval.
        """
        has_raw_path = "raw_path" in context
        has_keyword  = any(kw in lowered for kw in _INGEST_KEYWORDS)

        if has_raw_path or has_keyword:
            logger.debug(
                "Planner: Priority 1 matched (raw_path=%s, keyword=%s).",
                has_raw_path, has_keyword,
            )
            return RoutingPlan(
                agent          = "wiki_agent",
                fetch_episodic = False,
                fetch_rag      = False,
                priority       = 1,
            )
        return None

    # -----------------------------------------------------------------------
    # Priority 1b — Diff-only wiki update
    # -----------------------------------------------------------------------

    def _priority1b_diff(
        self,
        instruction: str,
        lowered:     str,
    ) -> RoutingPlan | None:
        """
        Priority 1b — diff-only wiki update ("update page X to reflect Y",
        with no raw file involved). Only reached when Priority 1 (ingest)
        did not already match, so an ingest instruction that happens to
        also contain a diff keyword still takes the ingest path unchanged.

        Resolves the target page name via the same resolve_graph_target()
        three-tier pipeline Priority 3c uses, fed by
        memory_manager.list_graph_node_stems(). On successful resolution,
        routes to wiki_agent with diff_target set. On a keyword match with
        failed/ambiguous resolution (or no MemoryManager to resolve
        against), routes to conversational_agent with no tools/retrieval so
        the model can ask the user which page they mean — the turn is
        claimed either way; it deliberately does NOT fall through to P2+
        on an unresolved target. Both P1 and P1b are "write to storage"
        intents and stay on the same deterministic, early footing ahead of
        P2 memory commands (Michael's decision, 2026-07-09).

        Returns None only when no _DIFF_KEYWORDS lead phrase is present.
        """
        remainder = extract_diff_query(instruction)
        if remainder is None:
            return None

        if self._memory_manager is None:
            logger.debug(
                "Planner: Priority 1b matched keyword but no MemoryManager — "
                "routing to conversational_agent for clarification."
            )
            return RoutingPlan(
                agent          = "conversational_agent",
                fetch_episodic = False,
                fetch_rag      = False,
                priority       = 1,
            )

        try:
            candidate_stems = self._memory_manager.list_graph_node_stems()
        except Exception as exc:
            logger.warning(
                "Planner: Priority 1b — list_graph_node_stems failed: %s", exc
            )
            candidate_stems = []

        resolved_stem = resolve_graph_target(remainder, candidate_stems)

        if resolved_stem is None:
            logger.debug(
                "Planner: Priority 1b — target resolution failed for %r; "
                "routing to conversational_agent for clarification.",
                remainder,
            )
            return RoutingPlan(
                agent          = "conversational_agent",
                fetch_episodic = False,
                fetch_rag      = False,
                priority       = 1,
            )

        logger.debug(
            "Planner: Priority 1b matched — diff_target=%r.", resolved_stem
        )
        return RoutingPlan(
            agent          = "wiki_agent",
            fetch_episodic = False,
            fetch_rag      = False,
            priority       = 1,
            diff_target    = resolved_stem,
        )

    # -----------------------------------------------------------------------
    # Priority 2 — Explicit memory command  (§4.2, Priority 2)
    # -----------------------------------------------------------------------

    def _priority2_memory(self, lowered: str) -> RoutingPlan | None:
        """
        Match condition: any memory command keyword present in lowercased
        instruction.

        Sets write_episode=True. The episode_type hint is left as None here
        — the EpisodicMemoryWriter will infer type from content. After
        writing, routing continues to Priority 4 or 6 for the response; the
        compound flag is set to True to signal that sequencing is needed.

        Returns a RoutingPlan or None if no match.
        """
        matched_kw = next(
            (kw for kw in _MEMORY_KEYWORDS if kw in lowered), None
        )
        if matched_kw is not None:
            logger.debug(
                "Planner: Priority 2 matched (keyword=%r).", matched_kw
            )
            return RoutingPlan(
                agent          = "conversational_agent",
                fetch_episodic = False,
                fetch_rag      = False,
                write_episode  = True,
                episode_type   = None,   # extracted by EpisodicMemoryWriter
                compound       = True,   # write first, then respond
                priority       = 2,
            )
        return None

    # -----------------------------------------------------------------------
    # Priority 3 — Tool signal  (§4.2, Priority 3)
    # -----------------------------------------------------------------------

    @staticmethod
    def _any_whole_word(keywords: frozenset[str], text: str) -> str | None:
        """
        Return the first keyword from `keywords` that appears as a whole
        word (or whole phrase) in `text`, or None if no match.

        Multi-word keywords (e.g. "create a file") are matched as a literal
        phrase with word boundaries on each end. Single-word keywords are
        matched with \\b anchors. Matching is case-insensitive; callers
        should pass already-lowercased text.
        """
        for kw in keywords:
            pattern = r"\b" + re.escape(kw) + r"\b"
            if re.search(pattern, text):
                return kw
        return None

    def _semantic_search_intent(
        self, lowered: str
    ) -> tuple[str, float, dict[str, float]] | None:
        """
        Diagnostic-only (Slot [Diagnostic 2]): returns the best-matching
        group, its score, AND the max score per group across all groups —
        so collisions between groups can be inspected directly, not just
        inferred from the argmax.

        Returns (best_group, best_score, all_group_scores) or None under:
        no embed_fn, embedding failure, no group scored above -1, or a
        confirmed negative-filter suppression (see below).

        2026-07-16 redesign (negative-filter conflict resolution): prior to
        this, _SEARCH_NEGATIVE_FILTER / _RESEARCH_NEGATIVE_FILTER were
        checked BEFORE the embedding was computed, so (a) no score was ever
        available to log for a filtered turn, contrary to how this method
        is described elsewhere as running "on every turn", and (b) a filter
        match on one group's known collision (e.g. lookup_request's
        greeting/identity phrases) suppressed ALL groups' gating that turn,
        research_intent included, not just the group the filter targets.

        Scores are now always computed first. The negative filters are
        checked AFTER scoring, and only escalate to a model call
        (_resolve_negative_filter_conflict) when there's a genuine
        conflict — a filter phrase matched AND some gated group's score
        cleared its own threshold anyway. If nothing cleared threshold,
        the filter and the embedding already agree (nothing was going to
        fire) and no call is needed — empirically the common case: see
        diagnostics/reports/negative_filter_tiebreak_assessment_2026-07-16.md
        §3, where only 4-8 of 11 filter-matched test utterances (depending
        on LOCALIST_RESEARCH_LOOP_ENABLED) actually reached a conflict.
        """
        if (
            self._embed_fn is None
            or not self._template_embeddings
            or self._semantic_gating_disabled
        ):
            return None

        try:
            query_vec = self._embed_fn(lowered)
        except Exception as exc:  # noqa: BLE001
            logger.warning(
                "Planner: _semantic_search_intent — embed_fn raised: %s", exc,
            )
            return None

        # Per-group max scores: accumulate highest similarity for each group.
        group_scores: dict[str, float] = {g: -1.0 for g in _SEARCH_INTENT_TEMPLATES}
        for group_name, tmpl_vec in self._template_embeddings:
            score = _cosine_similarity(query_vec, tmpl_vec)
            if score > group_scores[group_name]:
                group_scores[group_name] = score

        best_group = max(group_scores, key=lambda g: group_scores[g])
        best_score = group_scores[best_group]

        if best_score < 0:
            return None

        matched_phrase = next(
            (p for p in _ALL_SEARCH_NEGATIVE_FILTERS if p in lowered), None
        )
        if matched_phrase is not None:
            # research_intent is only a "gated" group worth resolving a
            # conflict over when the research loop is actually enabled —
            # otherwise nothing acts on its score regardless.
            gated_groups = dict(_SEMANTIC_GATE_THRESHOLDS)
            if self._research_loop_enabled():
                gated_groups["research_intent"] = _RESEARCH_INTENT_THRESHOLD

            conflicting = [
                g for g, t in gated_groups.items() if group_scores.get(g, -1.0) >= t
            ]
            if not conflicting:
                # Filter and embedding already agree — nothing was going to
                # fire anyway. No model call needed.
                logger.debug(
                    "Planner: Priority 3 semantic check — negative filter %r "
                    "matched but no group cleared threshold; no conflict.",
                    matched_phrase,
                )
                return None

            if not self._resolve_negative_filter_conflict(lowered, matched_phrase):
                logger.debug(
                    "Planner: Priority 3 semantic check — negative filter %r "
                    "confirmed by tie-break over conflicting group(s) %s; "
                    "suppressing.",
                    matched_phrase, conflicting,
                )
                return None

            logger.debug(
                "Planner: Priority 3 semantic check — negative filter %r "
                "overridden by tie-break for group(s) %s.",
                matched_phrase, conflicting,
            )

        return (best_group, best_score, group_scores)

    def _resolve_negative_filter_conflict(
        self, lowered: str, matched_phrase: str
    ) -> bool:
        """
        Single bounded inference call — the SAME "one classifier call,
        yes/no or single-word answer" shape as the Priority 5
        episodic-relevance check and the P6-fallthrough tool-need
        classifier. Only reached when a negative-filter phrase matched AND
        at least one semantically-gated group cleared its threshold
        anyway; the common case (filter matches, nothing near threshold)
        never gets here, so this should be rare in practice, not a
        per-turn cost — confirmed empirically (not assumed) in
        diagnostics/reports/negative_filter_tiebreak_assessment_2026-07-16.md
        §3: 4/11 (research loop off) to 8/11 (on) filter-matched
        utterances actually reach this call.

        Returns True to override the filter (real lookup intent — let
        best_group/best_score through) or False to confirm the filter's
        suppression (return None from the caller).

        Fails closed: any runtime error, timeout, or unparseable response
        suppresses the match (returns False) — a live failure here should
        not accidentally let a known collision phrase through gating;
        same fail-safe direction _research_loop_enabled() and every other
        gate in this file already defaults to.

        Accuracy validated before wiring this in: 11/11 (100%) on the
        operationally-reachable subset of the 2026-07-16 diagnostic's
        37-utterance test set (0 false positives — a real Category E
        opinion incorrectly let through — and 0 false negatives — a real
        lookup incorrectly suppressed).
        """
        try:
            raw = self._runtime.infer(
                system      = _NEGATIVE_FILTER_TIEBREAK_SYSTEM_PROMPT,
                prompt      = f"Instruction: {lowered}\n\nClassification (lookup/other):",
                max_tokens  = 10,
                temperature = 0.1,
            )
            return raw.strip().lower().startswith("lookup")
        except Exception as exc:
            logger.debug(
                "Planner: negative-filter tie-break failed (%s); suppressing.", exc
            )
            return False

    @staticmethod
    def _research_loop_enabled() -> bool:
        """
        Read LOCALIST_RESEARCH_LOOP_ENABLED from the environment.

        Read at call time (not cached at construction) — same rationale as
        _tool_fallback_mode(): flipping backend/.env shouldn't require
        reconstructing the Planner. Defaults to disabled; unset or any
        value other than "true" (case-insensitive) is "off" — fail-safe to
        zero behavior change (plain web_search) rather than fail-open into
        the loop.
        """
        return os.environ.get(_RESEARCH_LOOP_ENV_VAR, "false").strip().lower() == "true"

    def _priority3_tool(
        self, lowered: str, instruction: str | None = None
    ) -> RoutingPlan | None:
        """
        Match condition: web search keyword, explicit-date pattern, semantic
        search-intent gate, chart keyword, OR file operation keyword present
        in lowercased instruction — see _WEB_SEARCH_KEYWORDS,
        _has_explicit_date(), _SEMANTIC_GATE_THRESHOLDS, and _CHART_KEYWORDS
        respectively; any one alone is sufficient.

        Populates tools_to_call with "web_search", "chart", and/or "file_op"
        as appropriate. Sets compound=True when a tool is scheduled alongside
        a response agent, since the tool must run before the agent call.

        file_op is detected via either a literal _FILE_OP_KEYWORDS hit (read/
        open/create) or a filename-destination phrase from
        _FILE_OP_PATH_PATTERNS ("save it as X.ext", "name it X.ext", "call it
        X.ext") — the latter catches write/save instructions that don't use
        one of the narrow trigger keywords, e.g. "write a haiku about the sea
        and save it as haiku.md". Once file_op is matched, a write/append
        action additionally needs content to write. If that content is
        already present in the instruction (fenced code block, quoted span,
        or "with the content"/"containing"/"that says" phrasing — same
        signal _derive_file_op_content() extracts from at dispatch time),
        behavior is unchanged: "file_op" is added to tools_to_call. If no
        such content is present, the content must be generated by the agent
        first, so "file_op" is deliberately left out of tools_to_call (there
        is nothing to dispatch yet) and file_op_deferred/file_op_path/
        file_op_action are set instead so a future controller step can
        dispatch file_op once generation completes. A bare read action never
        needs content, so it always takes the tools_to_call=["file_op"] path
        regardless of content presence.

        `instruction` (original case) is optional and defaults to `lowered`
        when omitted — every existing direct caller of this method (tests
        included) passes only the lowered string, and content/path
        derivation below tolerates lowered input fine (quotes/fences aren't
        case-sensitive; _derive_file_op_content's phrase pattern and the
        destination patterns are already re.IGNORECASE). Passing the raw
        instruction (as route() does) only improves case fidelity of the
        derived file_op_path/file_op_action in the deferred branch.

        Returns a RoutingPlan or None if no match.
        """
        tools: list[str] = []

        ws_kw = self._any_whole_word(_WEB_SEARCH_KEYWORDS, lowered)
        if ws_kw:
            tools.append("web_search")
            logger.debug(
                "Planner: Priority 3 — web_search signal detected (%r).", ws_kw
            )

        chart_kw = self._any_whole_word(_CHART_KEYWORDS, lowered)
        if chart_kw:
            tools.append("chart")
            logger.debug(
                "Planner: Priority 3 — chart signal detected (%r).", chart_kw
            )

        semantic_result = self._semantic_search_intent(lowered)
        semantic_triggered = False
        fired_groups: list[str] = []
        if semantic_result is not None:
            best_group, best_score, all_scores = semantic_result
            fired_groups = [
                group for group, threshold in _SEMANTIC_GATE_THRESHOLDS.items()
                if all_scores.get(group, 0.0) >= threshold
            ]
            semantic_triggered = bool(fired_groups)
            logger.debug(
                "Planner: Priority 3 — semantic signal best=%r(%.3f) all=%s "
                "gate_fired=%s.",
                best_group, best_score, all_scores, semantic_triggered,
            )

        if _has_explicit_date(lowered) and "web_search" not in tools:
            tools.append("web_search")
            logger.debug(
                "Planner: Priority 3 — web_search signal detected via "
                "explicit-date pattern."
            )

        if semantic_triggered and "web_search" not in tools:
            tools.append("web_search")
            fired_str = ", ".join(
                f"{group}={all_scores[group]:.3f}(>={_SEMANTIC_GATE_THRESHOLDS[group]:.2f})"
                for group in fired_groups
            )
            logger.debug(
                "Planner: Priority 3 — web_search signal detected via semantic "
                "gate (fired=[%s]).", fired_str,
            )

        # research_intent upgrade: decide web_search vs research using the
        # SAME semantic_result already computed above; no second embed call.
        # research_intent only ever decides which tool variant fires, given
        # web_search already fired for some other reason — it is not itself
        # a gate on whether a tool fires at all (see the module-level note
        # above _RESEARCH_LOOP_ENV_VAR), which is why it lives outside
        # _SEMANTIC_GATE_THRESHOLDS rather than as an entry in it.
        if (
            "web_search" in tools
            and semantic_result is not None
            and self._research_loop_enabled()
        ):
            _, _, all_scores = semantic_result
            research_score = all_scores.get("research_intent", -1.0)
            if research_score >= _RESEARCH_INTENT_THRESHOLD:
                tools[tools.index("web_search")] = "research"
                logger.debug(
                    "Planner: Priority 3 — upgraded web_search to research "
                    "(research_intent=%.3f >= %.2f).",
                    research_score, _RESEARCH_INTENT_THRESHOLD,
                )

        raw = instruction if instruction is not None else lowered

        fo_kw = self._any_whole_word(_FILE_OP_KEYWORDS, lowered)
        fo_dest_match: str | None = None
        if not fo_kw:
            for pattern in _FILE_OP_PATH_PATTERNS:
                if pattern.search(raw):
                    fo_dest_match = pattern.pattern
                    break

        file_op_deferred = False
        file_op_path:   str | None = None
        file_op_action: str | None = None

        if fo_kw or fo_dest_match:
            action = _derive_file_op_action(raw)
            content_needed  = action in ("write", "append")
            content_present = bool(_derive_file_op_content(raw))

            if not content_needed or content_present:
                tools.append("file_op")
                logger.debug(
                    "Planner: Priority 3 — file_op signal detected "
                    "(kw=%r dest_match=%r action=%r content_present=%s).",
                    fo_kw, fo_dest_match, action, content_present,
                )
            else:
                file_op_deferred = True
                file_op_path   = _derive_file_op_path(raw)
                file_op_action = action
                logger.debug(
                    "Planner: Priority 3 — file_op signal detected but "
                    "content is generation-required (kw=%r dest_match=%r "
                    "action=%r path=%r); deferring dispatch until content "
                    "exists.",
                    fo_kw, fo_dest_match, action, file_op_path,
                )

        if self._any_whole_word(_FETCH_KEYWORDS, lowered) or re.search(
            r"https?://", lowered
        ):
            tools.append("url_fetch")
            logger.debug("Planner: Priority 3 — url_fetch signal detected.")

        if tools or file_op_deferred:
            return RoutingPlan(
                agent          = "conversational_agent",
                fetch_episodic = False,
                fetch_rag      = False,
                tools_to_call  = tools,
                compound       = True,
                priority       = 3,
                tool_signal_source = "keyword",
                file_op_deferred = file_op_deferred,
                file_op_path     = file_op_path,
                file_op_action   = file_op_action,
            )
        return None

    # -----------------------------------------------------------------------
    # Priority 3c — Graph-query  (structural link lookup)
    # -----------------------------------------------------------------------

    def _priority3c_graph_query(
        self,
        instruction: str,
        lowered:     str,
    ) -> RoutingPlan | None:
        """
        Priority 3c — Graph-query (structural "what links to X" /
        "what does X link to" lookup).

        Wins over web_search/P3b/P4a/P4 but loses to P1/P2 (handled by
        route()'s call order, not here) and to P3's file_op/url_fetch
        signals specifically (handled by the inline guard below — there is
        no standalone pre-check method for those two signals; the module-
        level note above _priority3_tool() explains the design rationale —
        do NOT remove that comment when editing nearby code).

        Returns None (deferring to normal priority evaluation) if:
          - file_op or url_fetch keywords are present (inline guard), OR
          - no MemoryManager is available, OR
          - no extraction pattern matches the instruction, OR
          - name resolution fails at all tiers (zero or ambiguous matches).

        On success, returns a RoutingPlan with graph_query set and
        fetch_rag/fetch_episodic all False — graph-query turns are deliberately
        pure/minimal, never combined with RAG or episodic context (Phase C design).
        """
        # 1. Inline file_op/url_fetch guard.
        #    Intentionally duplicates _priority3_tool()'s file_op/url_fetch
        #    detection — this duplication is deliberate (no standalone
        #    pre-check exists for those two signals without modifying
        #    _priority3_tool()). The _FILE_OP_PATH_PATTERNS check mirrors
        #    _priority3_tool()'s destination-phrase signal ("save it as
        #    X.ext" etc.) so P3c still defers to P3 for file_op instructions
        #    that only match via that signal (no _FILE_OP_KEYWORDS hit) —
        #    keep both in sync if either changes.
        #    _WEB_SEARCH_KEYWORDS is NOT guarded here: P3c must win over a
        #    web_search-only P3 match (hence its placement before P3 in route()).
        if (
            self._any_whole_word(_FILE_OP_KEYWORDS, lowered)
            or any(p.search(instruction) for p in _FILE_OP_PATH_PATTERNS)
            or self._any_whole_word(_FETCH_KEYWORDS, lowered)
            or re.search(r"https?://", lowered)
        ):
            return None

        # 2. MemoryManager availability check (same pattern as P3b/P4).
        if self._memory_manager is None:
            logger.debug("Planner: Priority 3c skipped — no MemoryManager.")
            return None

        # 3. Extraction.
        extracted = extract_graph_query(instruction)
        if extracted is None:
            return None
        direction, remainder = extracted

        # 4. Fetch candidate stems from the live graph_nodes table.
        try:
            candidate_stems = self._memory_manager.list_graph_node_stems()
        except Exception as exc:
            logger.warning(
                "Planner: Priority 3c — list_graph_node_stems failed: %s", exc
            )
            return None

        # 5. Name resolution (three-tier deterministic pipeline).
        resolved_stem = resolve_graph_target(remainder, candidate_stems)
        if resolved_stem is None:
            logger.debug(
                "Planner: Priority 3c — name resolution failed for %r.", remainder
            )
            return None

        # 6. Node id lookup.  Should always succeed since resolved_stem came
        #    from the same graph_nodes table, but guard defensively in case of
        #    a race between step 4 and step 6 in a concurrent-write scenario.
        try:
            node = self._memory_manager.resolve_node_by_stem(resolved_stem)
        except Exception as exc:
            logger.warning(
                "Planner: Priority 3c — resolve_node_by_stem failed: %s", exc
            )
            return None

        if node is None:
            logger.warning(
                "Planner: Priority 3c — resolve_node_by_stem returned None for "
                "%r (race condition or DB inconsistency).", resolved_stem
            )
            return None

        node_id = node["id"]
        logger.debug(
            "Planner: Priority 3c matched — direction=%r stem=%r node_id=%d.",
            direction, resolved_stem, node_id,
        )

        # 7. Build the plan.
        return RoutingPlan(
            agent          = "conversational_agent",
            fetch_episodic = False,
            fetch_rag      = False,
            compound       = False,
            priority       = 3,
            graph_query    = (direction, node_id, resolved_stem),
        )

    # -----------------------------------------------------------------------
    # Priority 3b — Factual query + corpus miss
    # -----------------------------------------------------------------------

    def _priority3b_factual(self, instruction: str, lowered: str) -> RoutingPlan | None:
        """
        Match condition: instruction contains a factual query keyword AND
        corpus query returns no result above _CORPUS_SCORE_THRESHOLD.

        When no MemoryManager is available, this priority is skipped entirely
        (returns None) — corpus cannot be checked.

        Returns a RoutingPlan with tools_to_call=["web_search"], or None.
        """
        if not any(kw in lowered for kw in _FACTUAL_QUERY_KEYWORDS):
            return None

        if self._memory_manager is None:
            logger.debug("Planner: Priority 3b skipped — no MemoryManager.")
            return None

        try:
            results = self._memory_manager.query_corpus(
                instruction, max_results=1
            )
        except Exception as exc:
            logger.warning("Planner: Priority 3b corpus check failed: %s", exc)
            results = []

        top_score = results[0].relevance_score if results else 0.0

        if top_score >= _CORPUS_SCORE_THRESHOLD:
            logger.debug(
                "Planner: Priority 3b — corpus hit (score=%.3f), "
                "deferring to Priority 4.", top_score,
            )
            return None

        logger.debug(
            "Planner: Priority 3b matched — factual keyword, "
            "corpus miss (score=%.3f), scheduling web_search.", top_score,
        )
        return RoutingPlan(
            agent          = "conversational_agent",
            fetch_episodic = False,
            fetch_rag      = False,
            tools_to_call  = ["web_search"],
            compound       = True,
            priority       = 3,
            tool_signal_source = "keyword",
        )

    # -----------------------------------------------------------------------
    # Priority 4 — Corpus signal  (§4.2, Priority 4)
    # -----------------------------------------------------------------------

    def _priority4_corpus(self, lowered: str, instruction: str) -> RoutingPlan | None:
        """
        Match condition (either sufficient):
          A) instruction contains an explicit wiki/vault trigger keyword, OR
          B) MemoryManager is available AND query_corpus() returns a top result
             with relevance_score >= _CORPUS_SCORE_THRESHOLD.

        Path A keeps routing deterministic for explicit wiki requests.
        Path B restores score-based RAG injection for natural-language corpus
        queries that lack a trigger keyword (e.g. "summarize the LORA Master
        Project Outline").

        Returns a RoutingPlan with fetch_rag=True, or None if no match.
        """
        # Path A — explicit keyword trigger
        matched_kw = next(
            (kw for kw in _WIKI_QUERY_KEYWORDS if kw in lowered), None
        )
        if matched_kw is not None:
            logger.debug(
                "Planner: Priority 4 matched via keyword (%r).", matched_kw
            )
            return RoutingPlan(
                agent          = "conversational_agent",
                fetch_episodic = True,
                fetch_rag      = True,
                compound       = False,
                priority       = 4,
            )

        # Path B — corpus score threshold
        if self._memory_manager is None:
            logger.debug("Planner: Priority 4 Path B skipped — no MemoryManager.")
            return None

        try:
            results = self._memory_manager.query_corpus(
                instruction, max_results=1
            )
        except Exception as exc:
            logger.warning("Planner: Priority 4 corpus check failed: %s", exc)
            return None

        top_score = results[0].relevance_score if results else 0.0

        if top_score >= _CORPUS_SCORE_THRESHOLD:
            logger.debug(
                "Planner: Priority 4 matched via corpus score (%.3f >= %.3f).",
                top_score, _CORPUS_SCORE_THRESHOLD,
            )
            return RoutingPlan(
                agent          = "conversational_agent",
                fetch_episodic = False,
                fetch_rag      = True,
                compound       = False,
                priority       = 4,
            )

        logger.debug(
            "Planner: Priority 4 — corpus miss (top_score=%.3f).", top_score
        )
        return None

    # -----------------------------------------------------------------------
    # Priority 5 — Episodic relevance  (§4.2, §4.3)
    # -----------------------------------------------------------------------

    def _priority5_episodic(self, instruction: str) -> RoutingPlan | None:
        """
        Priority 5 — Episodic relevance (§4.2, §4.3).

        Replaced inference call with deterministic keyword check for
        Gemma 4B compatibility. The model requires max_tokens=300 to
        produce binary classifier output, making inference-based routing
        too expensive for a per-turn call.

        Returns a RoutingPlan with fetch_episodic=True if the instruction
        contains episodic relevance signals, or None if not.

        Session flag caching is preserved: once episodic bullets have been
        injected this session, all subsequent turns return fetch_episodic=True
        without keyword evaluation.
        """
        # Cache check: session-level flag.
        # When set, we skip the (previously: inference) call and go straight
        # to keyword evaluation — but we do NOT return True unconditionally.
        # A turn with no episodic keyword still returns None so P6 or P4 can
        # handle it correctly.
        _skip_inference = self._episodic_injected
        if _skip_inference:
            logger.debug(
                "Planner: Priority 5 — episodic_injected=True; "
                "skipping inference, proceeding to keyword check."
            )

        # Deterministic keyword check
        _EPISODIC_KEYWORDS: frozenset[str] = frozenset({
            "preference", "preferences", "remember", "remembered",
            "you know about me", "what do you know",
            "decision", "decisions", "decided",
            "correction", "corrections", "wrong",
            "workflow", "workflows",
            "last time", "previously", "before",
            "my project", "my setup", "my environment",
            # Personal reference signals (unambiguous — always fetch episodic)
            "my name", "do you remember", "who am i",
            "what do you know about me", "my preference",
            "what did i tell you", "what have i told you",
        })

        lowered = instruction.lower()
        matched = next(
            (kw for kw in _EPISODIC_KEYWORDS if kw in lowered), None
        )

        if matched:
            logger.debug(
                "Planner: Priority 5 — episodic keyword matched %r → "
                "fetch_episodic=True.", matched
            )
            return RoutingPlan(
                agent          = "conversational_agent",
                fetch_episodic = True,
                fetch_rag      = False,
                priority       = 5,
            )

        logger.debug("Planner: Priority 5 — no episodic keyword matched.")
        return None

    # -----------------------------------------------------------------------
    # P6-fallthrough tool-need classifier  (feature-flagged, shadow-first)
    # -----------------------------------------------------------------------

    @staticmethod
    def _tool_fallback_mode() -> str:
        """
        Read LOCALIST_TOOL_FALLBACK_CLASSIFIER from the environment.

        Read at call time (not cached) so tests and ops tooling can flip
        modes without reconstructing the Planner. Any value other than
        "off" / "shadow" / "active" (including unset) is treated as "off" —
        fail-safe to zero behavior change.
        """
        mode = os.environ.get(_TOOL_FALLBACK_ENV_VAR, "off").strip().lower()
        return mode if mode in _TOOL_FALLBACK_VALID_MODES else "off"

    def _classify_tool_fallback(
        self,
        instruction: str,
        context:     dict[str, Any],
    ) -> str | None:
        """
        Bounded single-inference-call classifier: "is a tool needed for this
        instruction, and which one?" Called only when P1, P2, P3/3b/3c, and
        P4 have all found no match for this turn (i.e. routing is about to
        fall through past Priority 5 toward Priority 6) AND the
        LOCALIST_TOOL_FALLBACK_CLASSIFIER flag is "shadow" or "active" (see
        _maybe_tool_fallback_classifier — when the flag is "off", this
        method is never called at all).

        Two hard gates run before any model call:

          Gate 1 — deterministic, not a model judgment: skip if the most
          recently completed turn's tools_to_call was non-empty (tracked in
          self._last_turn_tools_fired, updated by route()/record_tools_fired()
          after every turn). This makes the "tool need was already resolved
          last turn" failure mode structurally impossible rather than
          something the model is asked to avoid.

          Gate 2 — dependency check: skip if memory_manager or runtime is
          unavailable, the same fail-open-to-existing-behavior pattern
          Priority 4/5 already use when their dependencies are absent.

        The model is asked for exactly one word — one of web_search,
        file_op, url_fetch, or none — and nothing else. Parsed via strict
        exact-match (after .strip().lower()) against that known set; any
        other output (empty, prose, garbage) parses to None, same as "none".
        No arguments are requested from or derived from the model's output;
        query/path/url resolution for whichever tool name is returned stays
        entirely with the existing deterministic derivation logic
        (MCPToolDispatcher), exactly as it already runs today for P3/P3b
        tools_to_call matches.

        Returns the parsed tool name, or None (no tool needed, gate skip,
        or any parse/inference failure). Never raises.
        """
        if os.environ.get(self._GATE1_ENV_VAR, "on").strip().lower() != "off":
            if self._last_turn_tools_fired:
                logger.info(
                    "Planner: tool-fallback classifier — instruction=%r gate1_pass=False "
                    "(prior turn tools_fired=%r); skipping.",
                    instruction, self._last_turn_tools_fired,
                )
                return None
        else:
            logger.info(
                "Planner: tool-fallback classifier — instruction=%r Gate 1 disabled via %s=off "
                "(prior turn tools_fired=%r, would have gated if enabled).",
                instruction, self._GATE1_ENV_VAR, self._last_turn_tools_fired,
            )

        if self._memory_manager is None or self._runtime is None:
            logger.info(
                "Planner: tool-fallback classifier — instruction=%r gate1_pass=True "
                "gate2_pass=False (memory_manager_present=%s, runtime_present=%s); "
                "skipping.",
                instruction,
                self._memory_manager is not None,
                self._runtime is not None,
            )
            return None

        prompt = (
            f"User instruction: {instruction}\n\n"
            "Does answering this require calling an external tool? Respond "
            "with exactly one word: web_search, file_op, url_fetch, or none."
        )

        try:
            raw = self._runtime.infer(
                prompt,
                system      = _TOOL_FALLBACK_SYSTEM_PROMPT,
                max_tokens  = 8,
                temperature = 0.0,
            )
        except Exception as exc:  # noqa: BLE001
            logger.warning(
                "Planner: tool-fallback classifier — instruction=%r gate1_pass=True "
                "gate2_pass=True runtime.infer raised: %s; treating as None.",
                instruction, exc,
            )
            return None

        parsed = raw.strip().lower()
        tool = parsed if parsed in _TOOL_FALLBACK_TOOL_NAMES else None

        logger.info(
            "Planner: tool-fallback classifier — instruction=%r gate1_pass=True "
            "gate2_pass=True raw_output=%r parsed_tool=%r.",
            instruction, raw, tool,
        )
        return tool

    def _maybe_tool_fallback_classifier(
        self,
        instruction: str,
        context:     dict[str, Any],
    ) -> RoutingPlan | None:
        """
        Feature-flag wrapper around _classify_tool_fallback().

          off    (default) — returns None immediately; _classify_tool_fallback
                              is never called. Zero behavior change, zero
                              latency change.
          shadow            — _classify_tool_fallback runs (and logs), but
                              the result is discarded here: this method
                              still returns None, so route() proceeds to
                              _priority6_direct() exactly as it would with
                              the flag off. For observing real traffic
                              before the classifier is trusted to touch
                              routing.
          active            — a parsed tool name sets tools_to_call on a new
                              RoutingPlan as P3 would have, tagged
                              tool_signal_source="classifier_fallback" so
                              it is never confused with a keyword match in
                              per-turn metadata. A parsed None (no tool
                              needed) returns None here too, deferring to
                              _priority6_direct().
        """
        mode = self._tool_fallback_mode()
        if mode == "off":
            return None

        tool = self._classify_tool_fallback(instruction, context)

        if mode == "shadow":
            logger.info(
                "Planner: tool-fallback classifier — shadow mode, parsed_tool=%r "
                "discarded; RoutingPlan unaffected.", tool,
            )
            return None

        # mode == "active"
        if tool is None:
            return None

        logger.info(
            "Planner: tool-fallback classifier — active mode, tools_to_call=[%r] "
            "via classifier_fallback.", tool,
        )
        return RoutingPlan(
            agent              = "conversational_agent",
            fetch_episodic     = False,
            fetch_rag          = False,
            tools_to_call      = [tool],
            compound           = True,
            priority           = 6,
            tool_signal_source = "classifier_fallback",
        )

    # -----------------------------------------------------------------------
    # Priority 6 — Direct answer fallback  (§4.2, Priority 6)
    # -----------------------------------------------------------------------

    def _priority6_direct(self) -> RoutingPlan:
        """
        Priority 6 — Direct answer fallback (§4.2, Priority 6).

        Reached only when no prior priority matched. Routes to
        ConversationalAgent with no retrieval — the model answers from
        its own weights plus working memory (slots 1–3 only).
        """
        logger.debug("Planner: Priority 6 — direct answer fallback.")
        return RoutingPlan(
            agent          = "conversational_agent",
            fetch_episodic = False,
            fetch_rag      = False,
            priority       = 6,
        )
